# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version:  2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

build:
  image: latest

#conda:
#  environment: doc/environment.yml

python:
   version: 3.6
   #system_packages: true
   requirements_file: doc/requirements.txt
