# -*- coding: utf-8 -*-
#
# add_prolog.py
#
# This file is part of NEST.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.

# This python file is a script to include
# the prolog required to run ebrains button
# to each python exmaple
# REcommeneded to add to python example 
# becasuse the examples are auto-generated by
# sphinx-gallery and the rst output states 
# that it should not be modified (relat3d to line numbers in 
# example scripts)

import os
import sys
from pathlib import Path
import glob


example_prolog = """

.. only:: html

  .. card:: Run this example as a Jupyter notebook
    :margin: auto
    :width: 50%
    :text-align: center

    .. image:: https://nest-simulator.org/TryItOnEBRAINS.png
         :target: https://lab.ebrains.eu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fnest%2Fnest-simulator-examples&urlpath=lab%2Ftree%2Fnest-simulator-examples%2Fnotebooks%2Fnotebooks%2Ffilepath.ipynb&branch=main

    For details and troubleshooting see :ref:`run_jupyter`.

"""
# Inject prolog into Python example
files = glob.glob('../../pynest/examples/**/*.py', recursive = True)
for file in files:

    lines = []
    with open(file, 'r') as f:
        name = os.path.basename(file)
        # get the path of file only
        path2dir = os.path.dirname(file)
        # get the last segement of path
        path2sub = os.path.basename(path2dir)
        # no extension
        name_noext = os.path.splitext(name)[0]

        if path2sub != "examples":
            path2example = path2sub + "%2F" + name_noext
        #   #    #links = link_puller.replace('one_neuron_with_noise.ipynb', link_sub_path)
            prolog = example_prolog.replace('filepath', path2example)
        #   #    print(html_context)


        else:
            path2example = os.path.splitext(name)[0]
            prolog = example_prolog.replace('filepath', path2example)


        lines = f.readlines()

    # index for prolog should be 2 lines below title line '-----'
    lines.insert(25, prolog + '\n')
#            if line.startswith('-----'):
                #lines.append(prolog + '\n')
#            else:
#                lines.append(line)

    with open(file, 'w') as f:
       lines = "".join(lines)
       f.write(lines)
      #  for line in lines :
      #      f.write(line)

           # get the filename only from the path
#          # Create proper links for nbgitpuller for each notebook
#       # check if subdirectory
#

