nest::GridLayer
typedef Position< D > nest::GridLayer< D >::key_type
typedef size_t nest::GridLayer< D >::mapped_type
typedef std::pair< Position< D >, size_t > nest::GridLayer< D >::value_type
typedef value_type& nest::GridLayer< D >::reference
typedef const value_type& nest::GridLayer< D >::const_reference
Position< D, size_t > nest::GridLayer< D >::dims_
number of nodes in each direction.
Referenced by nest::GridLayer< D >::masked_iterator::masked_iterator.
nest::GridLayer< D >::GridLayer()
nest::GridLayer< D >::GridLayer(const GridLayer &layer)
Position< D > nest::GridLayer< D >::get_position(size_t sind) const
Get position of node.
Only possible for local nodes. sind index of node position of node.
Position< D > nest::GridLayer< D >::lid_to_position(size_t lid) const
Get position of node.
Also allowed for non-local nodes. lid local index of node position of node.
size_t nest::GridLayer< D >::gridpos_to_lid(Position< D, int > pos) const
Position< D > nest::GridLayer< D >::gridpos_to_position(Position< D, int > gridpos) const
std::vector< std::pair< Position< D >, size_t > > nest::GridLayer< D >::get_global_positions_vector(const AbstractMask &mask, const Position< D > &anchor, bool allow_oversized, NodeCollectionPTR node_collection)
References nest::names::anchor, nest::names::mask, nest::GridLayer< D >::masked_begin, nest::GridLayer< D >::masked_end, nest::names::positions.
GridLayer< D >::masked_iterator nest::GridLayer< D >::masked_begin(const Mask< D > &mask, const Position< D > &anchor)
References nest::names::anchor, nest::names::mask.
Referenced by nest::GridLayer< D >::get_global_positions_vector.
GridLayer< D >::masked_iterator nest::GridLayer< D >::masked_end()
Referenced by nest::GridLayer< D >::get_global_positions_vector.
Position< D, size_t > nest::GridLayer< D >::get_dims() const
Referenced by nest::MaskedLayer< D >::check_mask_.
void nest::GridLayer< D >::set_status(const DictionaryDatum &d)
Change properties of the layer according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::center, nest::names::d, nest::names::extent, nest::Layer< D >::set_status, nest::names::shape.
void nest::GridLayer< D >::get_status(DictionaryDatum &d) const
Export properties of the layer by setting entries in the status dictionary.
d Dictionary.
References nest::names::d, nest::Layer< D >::get_status, nest::names::shape.
void nest::GridLayer< D >::insert_global_positions_(Ins iter, NodeCollectionPTR node_collection)
void nest::GridLayer< D >::insert_global_positions_ntree_(Ntree< D, size_t > &tree, NodeCollectionPTR node_collection)
Insert global position info into ntree.
References nest::Ntree< D, T, max_capacity, max_depth >::end.
void nest::GridLayer< D >::insert_global_positions_vector_(std::vector< std::pair< Position< D >, size_t > > &vec, NodeCollectionPTR node_collection)
Insert global position info into vector.