nest::CommonSynapseProperties
weight_recorder* nest::CommonSynapseProperties::weight_recorder_
nest::CommonSynapseProperties::CommonSynapseProperties()
Standard constructor.
Sets all common properties to default values. Default implementation of an empty CommonSynapseProperties object.
nest::CommonSynapseProperties::~CommonSynapseProperties()
void nest::CommonSynapseProperties::get_status(DictionaryDatum &d) const
Get all properties and put them into a dictionary.
References nest::NodeCollection::create, nest::names::d, nest::names::weight_recorder.
Referenced by nest::JonkeCommonProperties::get_status, nest::STDPDopaCommonProperties::get_status, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::get_status, nest::STDPPLHomCommonProperties::get_status, nest::STDPHomCommonProperties::get_status, nest::CommonPropertiesHomW::get_status.
void nest::CommonSynapseProperties::set_status(const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
References nest::names::d, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::node_manager, nest::KernelManager::vp_manager, nest::names::weight_recorder.
Referenced by nest::JonkeCommonProperties::set_status, nest::STDPDopaCommonProperties::set_status, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::set_status, nest::STDPPLHomCommonProperties::set_status, nest::STDPHomCommonProperties::set_status, nest::CommonPropertiesHomW::set_status.
void nest::CommonSynapseProperties::calibrate(const TimeConverter &)
Calibrate all time objects, which might be contained in this object.
long nest::CommonSynapseProperties::get_vt_node_id() const
Get node ID of volume transmitter.
weight_recorder * nest::CommonSynapseProperties::get_weight_recorder() const
Get weight_recorder.
Referenced by nest::Connector< ConnectionT >::send_weight_event.