nest::ModelManager
std::vector< Model* > nest::ModelManager::builtin_node_models_
List of clean built-in node models.
std::vector< Model* > nest::ModelManager::node_models_
List of usable node models.
This list is cleared and repopulated upon application startup and calls to ResetKernel. It contains copies of the built-in models, models registered from extension modules, and models created by calls to CopyModel(). The elements of this list also keep the user-modified defaults.
std::vector< ConnectorModel* > nest::ModelManager::builtin_connection_models_
List of built-in clean connection models.
std::vector< std::vector< ConnectorModel* > > nest::ModelManager::connection_models_
The list of usable connection models.
The first dimension keeps one entry per thread, the second dimension has the actual models. This list is cleared and repopulated upon application startup and calls to ResetKernel. The inner list contains copies of the built-in models, models registered from extension modules, and models created by calls to CopyModel(). The elements of the list also keep the user-modified defaults.
DictionaryDatum nest::ModelManager::modeldict_
Dictionary of all node models.
DictionaryDatum nest::ModelManager::synapsedict_
Dictionary of all synapse models.
Model* nest::ModelManager::proxynode_model_
std::vector< std::vector< Node* > > nest::ModelManager::proxy_nodes_
Placeholders for remote nodes, one per thread.
bool nest::ModelManager::model_defaults_modified_
True if any model defaults have been modified.
nest::ModelManager::ModelManager()
nest::ModelManager::~ModelManager() override
void nest::ModelManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References nest::VPManager::get_thread_id, nest::kernel, nest::names::model_id, nest::KernelManager::vp_manager.
Referenced by change_number_of_threads.
void nest::ModelManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
Referenced by change_number_of_threads.
void nest::ModelManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
References finalize, initialize.
void nest::ModelManager::set_status(const DictionaryDatum &) override
void nest::ModelManager::get_status(DictionaryDatum &) override
References nest::names::max_num_syn_models, nest::MAX_SYN_ID, nest::names::node_models, nest::names::synapse_models.
void nest::ModelManager::calibrate(const TimeConverter &)
Resize the structures for the Connector objects if necessary.
Functor to compare Models by their name. This function should be called after number of threads, min_delay, max_delay, and time representation have been changed in the scheduler. The TimeConverter is used to convert times from the old to the new representation. It is also forwarding the calibration request to all ConnectorModel objects.
References nest::kernel, nest::names::model.
Referenced by nest::SimulationManager::set_status.
Node * nest::ModelManager::get_proxy_node(size_t tid, size_t node_id)
Return a proxynode configured for thread tid and the given node_id.
References nest::ModelRangeManager::get_model_id, nest::kernel, nest::names::model_id, nest::KernelManager::modelrange_manager, nest::Node::set_vp.
Referenced by nest::NodeManager::get_mpi_local_node_or_device_head, nest::NodeManager::get_node_or_proxy.
ConnectorModel & nest::ModelManager::get_connection_model(synindex syn_id, size_t t=0)
Return pointer to protoype for given synapse id.
UnknownSynapseType
References assert_valid_syn_id.
Referenced by nest::TargetTableDevices::add_connection_from_device, nest::TargetTableDevices::add_connection_to_device, nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions, nest::ConnBuilder::connect, nest::ConnectionManager::deliver_secondary_events, get_secondary_event_prototype, nest::SPManager::get_status, nest::ConnectionManager::set_synapse_status.
const std::vector< ConnectorModel * > & nest::ModelManager::get_connection_models(size_t tid)
Referenced by nest::ConnectionManager::deliver_secondary_events.
size_t nest::ModelManager::register_node_model(const Name &name, std::string deprecation_info=std::string())
Register a node-model prototype.
This function must be called exactly once for each model class to make it known in the simulator. The natural place for a call to this function is in a *module.cpp file. name of the new node model. deprecation_info If non-empty string, deprecation warning will be issued for model with this info to user. ID of the new model object. register_prototype_connection
References nest::names::model.
size_t nest::ModelManager::copy_model(Name old_name, Name new_name, DictionaryDatum params)
Copy an existing model and register it as a new model.
This function allows users to create their own, cloned models. old_name name of existing model. new_name name of new model. params default parameters of new model. model ID of new Model object. copy_node_model_, copy_connection_model_
References nest::names::params.
Referenced by nest::copy_model, nest::NestModule::CopyModel_l_l_DFunction::execute.
bool nest::ModelManager::set_model_defaults(Name name, DictionaryDatum params)
Set the default parameters of a model.
name of model. params default parameters to be set. true if the operation succeeded, else false set_node_defaults_, set_synapse_defaults_
References nest::names::params.
void nest::ModelManager::register_connection_model(const std::string &name)
Register a synape model with a custom Connector model and without any common properties.
"hpc synapses" use TargetIdentifierIndex for ConnectionT and store the target neuron in form of a 2 Byte index instead of an 8 Byte pointer. This limits the number of thread local neurons to 65,536. No support for different receptor types. Otherwise identical to non-hpc version. When called, this function should be specialised by a class template, e.g. bernoulli_synapse< targetidentifierT > name The name under which the ConnectorModel will be registered.
References nest::ConnectorModel::has_property, nest::SUPPORTS_HPC, nest::SUPPORTS_LBL.
Referenced by nest::register_connection_model.
size_t nest::ModelManager::get_node_model_id(const Name) const
The model ID for a Model with a given name UnknownModelName if the model is not available
Referenced by nest::create, nest::AbstractLayer::create_layer, nest::get_model_defaults.
Model * nest::ModelManager::get_node_model(size_t) const
The Model registered with the given model ID
Referenced by nest::NodeManager::add_node, nest::Node::get_model_, nest::get_model_defaults, nest::ModelRangeManager::get_model_of_node_id, nest::Node::get_name, nest::proxynode::get_status, nest::NodeManager::print, nest::proxynode::send_test_event, nest::proxynode::sends_secondary_event, nest::proxynode::sends_signal.
size_t nest::ModelManager::get_synapse_model_id(std::string model_name)
The numeric ID of a given synapse model UnknownSynapseType if the model is not available
Referenced by nest::ConnBuilder::ConnBuilder, nest::ConnectionManager::connect, nest::ConnectionManager::connect_arrays, nest::ConnectionCreator::ConnectionCreator, nest::ConnectionManager::get_connections, nest::get_model_defaults, nest::GenericConnectorModel< ConnectionT >::get_status.
DictionaryDatum nest::ModelManager::get_connector_defaults(synindex syn_id) const
References assert_valid_syn_id, nest::KernelManager::connection_manager, nest::names::element_type, nest::ConnectionManager::get_num_connections, nest::kernel, nest::names::num_connections.
Referenced by nest::ConnBuilder::ConnBuilder, nest::ConnectionManager::connect_arrays, nest::ConnectionCreator::ConnectionCreator, nest::get_model_defaults, nest::SPBuilder::update_delay.
void nest::ModelManager::set_connector_defaults(synindex syn_id, const DictionaryDatum &d)
void nest::ModelManager::assert_valid_syn_id(synindex syn_id, size_t t=0) const
Asserts validity of synapse index, otherwise throws exception.
UnknownSynapseType
Referenced by nest::ConnectionManager::connect, get_connection_model, get_connector_defaults, get_secondary_event_prototype, nest::ConnectionManager::get_synapse_status, nest::ConnectionManager::set_synapse_status.
bool nest::ModelManager::are_model_defaults_modified() const
size_t nest::ModelManager::get_num_connection_models() const
References nest::invalid_synindex.
Referenced by nest::SourceTable::fill_compressed_spike_data, nest::ConnectionManager::get_connections, nest::SourceTable::resize_compressible_sources, nest::ConnectionManager::resize_connections.
void nest::ModelManager::memory_info() const
Print out the memory information for each node model.
References nest::Model::get_element_size, nest::Model::get_name, nest::Model::mem_available, nest::Model::mem_capacity, nest::sort.
SecondaryEvent & nest::ModelManager::get_secondary_event_prototype(const synindex syn_id, const size_t tid)
References assert_valid_syn_id, get_connection_model, nest::ConnectorModel::get_secondary_event.
Referenced by nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::deliver_secondary_events.
void nest::ModelManager::clear_node_models_()
void nest::ModelManager::clear_connection_models_()
size_t nest::ModelManager::register_node_model_(Model *model)
synindex nest::ModelManager::register_connection_model_(ConnectorModel *)
size_t nest::ModelManager::copy_node_model_(size_t old_id, Name new_name)
Copy an existing node model and register it as a new model.
old_id ID of existing model. new_name name of new model. model ID of new Model object. copy_model(), copy_connection_model_()
size_t nest::ModelManager::copy_connection_model_(size_t old_id, Name new_name)
Copy an existing synapse model and register it as a new model.
old_id ID of existing model. new_name name of new model. model ID of new Model object. copy_model(), copy_node_model_()
void nest::ModelManager::set_node_defaults_(size_t model_id, const DictionaryDatum &params)
Set the default parameters of a model.
model_id of model. params default parameters to be set. set_model_defaults, set_synapse_defaults_
void nest::ModelManager::set_synapse_defaults_(size_t model_id, const DictionaryDatum &params)
Set the default parameters of a model.
name of model. params default parameters to be set. set_model_defaults, set_node_defaults_
Node * nest::ModelManager::create_proxynode_(size_t t, int model_id)
bool nest::ModelManager::compare_model_by_id_(const int a, const int b)
Compares model ids for sorting in memory_info.