nest::static_synapse_hom_w
typedef CommonPropertiesHomW nest::static_synapse_hom_w< targetidentifierT >::CommonPropertiesType
typedef Connection< targetidentifierT > nest::static_synapse_hom_w< targetidentifierT >::ConnectionBase
constexpr ConnectionModelProperties nest::static_synapse_hom_w< targetidentifierT >::properties
void nest::static_synapse_hom_w< targetidentifierT >::get_status(DictionaryDatum &d) const
References nest::names::d, nest::names::size_of.
void nest::static_synapse_hom_w< targetidentifierT >::check_connection(Node &s, Node &t, size_t receptor_type, const CommonPropertiesType &)
References nest::Connection< targetidentifierT >::check_connection_, nest::names::receptor_type.
void nest::static_synapse_hom_w< targetidentifierT >::check_synapse_params(const DictionaryDatum &syn_spec) const
Checks to see if weight is given in syn_spec.
References nest::names::weight.
void nest::static_synapse_hom_w< targetidentifierT >::send(Event &e, const size_t tid, const CommonPropertiesHomW &cp)
Send an event to the receiver of this connection.
e The event to send tid Thread ID of the target cp Common properties-object of the synapse
References numerics::e, nest::static_synapse_hom_w< targetidentifierT >::get_delay_steps, nest::static_synapse_hom_w< targetidentifierT >::get_rport, nest::static_synapse_hom_w< targetidentifierT >::get_target, nest::CommonPropertiesHomW::get_weight.
void nest::static_synapse_hom_w< targetidentifierT >::set_weight(double)
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
Referenced by nest::static_synapse_hom_w< targetidentifierT >::send.
size_t nest::Connection< targetidentifierT >::get_rport() const
Referenced by nest::static_synapse_hom_w< targetidentifierT >::send.
Node* nest::Connection< targetidentifierT >::get_target(const size_t tid) const
Referenced by nest::static_synapse_hom_w< targetidentifierT >::send.