nest::TargetTableDevices
std::vector< std::vector< std::vector< ConnectorBase* > > > nest::TargetTableDevices::target_to_devices_
3d structure storing connections from neurons to devices
std::vector< std::vector< std::vector< ConnectorBase* > > > nest::TargetTableDevices::target_from_devices_
3d structure storing connections from devices to neurons
std::vector< std::vector< size_t > > nest::TargetTableDevices::sending_devices_node_ids_
3d structure storing node IDs of sending devices (necessary for get_connections)
nest::TargetTableDevices::TargetTableDevices()
nest::TargetTableDevices::~TargetTableDevices()
void nest::TargetTableDevices::initialize()
Initialize data structures.
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::finalize()
Delete data structure.
References boost::tuples::swap.
void nest::TargetTableDevices::add_connection_to_device(Node &source, Node &target, const size_t s_node_id, const size_t tid, const synindex syn_id, const DictionaryDatum &p, const double d, const double w)
Adds a connection from the neuron source to the device target.
References nest::ConnectorModel::add_connection, nest::names::d, nest::ModelManager::get_connection_model, nest::kernel, nest::KernelManager::model_manager, nest::VPManager::node_id_to_lid, nest::names::p, nest::names::source, nest::names::target, nest::KernelManager::vp_manager, nest::names::w.
void nest::TargetTableDevices::add_connection_from_device(Node &source, Node &target, const size_t tid, const synindex syn_id, const DictionaryDatum &p, const double d, const double w)
Adds a connection from the device source to the neuron target.
References nest::ConnectorModel::add_connection, nest::names::d, nest::ModelManager::get_connection_model, nest::kernel, nest::KernelManager::model_manager, nest::names::p, nest::names::source, nest::names::target, nest::names::w.
void nest::TargetTableDevices::send_to_device(const size_t tid, const size_t s_node_id, Event &e, const std::vector< ConnectorModel * > &cm)
Sends a spike event to all targets of the source neuron.
References numerics::e, nest::kernel, nest::VPManager::node_id_to_lid, nest::KernelManager::vp_manager.
Referenced by nest::ConnectionManager::send_to_devices.
void nest::TargetTableDevices::send_to_device(const size_t tid, const size_t s_node_id, SecondaryEvent &e, const std::vector< ConnectorModel * > &cm)
References numerics::e, nest::kernel, nest::VPManager::node_id_to_lid, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::send_from_device(const size_t tid, const size_t ldid, Event &e, const std::vector< ConnectorModel * > &cm)
Sends a spike event to all targets of the source device.
References numerics::e.
Referenced by nest::ConnectionManager::send_from_device.
void nest::TargetTableDevices::resize_to_number_of_neurons()
Resizes vectors according to number of local nodes.
References nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::ConnectionManager::resize_target_table_devices_to_number_of_neurons.
void nest::TargetTableDevices::resize_to_number_of_synapse_types()
Resizes vectors according to number of available synapse types.
References nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::ConnectionManager::resize_target_table_devices_to_number_of_synapse_types.
void nest::TargetTableDevices::get_connections_to_devices_(const size_t requested_source_node_id, const size_t requested_target_node_id, const size_t tid, const synindex synapse_id, const long synapse_label, std::deque< ConnectionID > &conns) const
Returns all connections from neurons to devices.
References nest::kernel, nest::VPManager::node_id_to_lid, nest::names::synapse_label, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::get_connections_to_device_for_lid_(const size_t lid, const size_t requested_target_node_id, const size_t tid, const synindex syn_id, const long synapse_label, std::deque< ConnectionID > &conns) const
Returns all connections from particular neuron to devices.
References nest::kernel, nest::VPManager::lid_to_node_id, nest::names::synapse_label, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::get_connections_from_devices_(const size_t requested_source_node_id, const size_t requested_target_node_id, const size_t tid, const synindex synapse_id, const long synapse_label, std::deque< ConnectionID > &conns) const
Returns all connections from devices to neurons.
References nest::NodeManager::get_node_or_proxy, nest::kernel, nest::KernelManager::node_manager, nest::names::source, nest::names::synapse_label.
void nest::TargetTableDevices::get_connections(const size_t requested_source_node_id, const size_t requested_target_node_id, const size_t tid, const synindex synapse_id, const long synapse_label, std::deque< ConnectionID > &conns) const
Returns all connections between neurons and devices.
References nest::names::synapse_label.
void nest::TargetTableDevices::get_synapse_status_to_device(const size_t tid, const size_t source_node_id, const synindex syn_id, DictionaryDatum &dict, const size_t lcid) const
Returns synapse status of connection from neuron to device.
References nest::kernel, nest::VPManager::node_id_to_lid, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::get_synapse_status_from_device(const size_t tid, const size_t ldid, const synindex syn_id, DictionaryDatum &dict, const size_t lcid) const
Returns synapse status of connection from device to neuron.
void nest::TargetTableDevices::set_synapse_status_to_device(const size_t tid, const size_t source_node_id, const synindex syn_id, ConnectorModel &cm, const DictionaryDatum &dict, const size_t lcid)
Sets synapse status of connection from neuron to device.
References nest::kernel, nest::VPManager::node_id_to_lid, nest::KernelManager::vp_manager.
void nest::TargetTableDevices::set_synapse_status_from_device(const size_t tid, const size_t ldid, const synindex syn_id, ConnectorModel &cm, const DictionaryDatum &dict, const size_t lcid)
Sets synapse status of connection from device to neuron.
bool nest::TargetTableDevices::is_device_connected(size_t tid, size_t lcid) const
Checks if the device has any connections in this thread.
Referenced by nest::ConnectionManager::get_device_connected.