nest::rate_connection_delayed
typedef CommonSynapseProperties nest::rate_connection_delayed< targetidentifierT >::CommonPropertiesType
typedef Connection< targetidentifierT > nest::rate_connection_delayed< targetidentifierT >::ConnectionBase
constexpr ConnectionModelProperties nest::rate_connection_delayed< targetidentifierT >::properties
double nest::rate_connection_delayed< targetidentifierT >::weight_
connection weight
nest::rate_connection_delayed< targetidentifierT >::rate_connection_delayed()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
SecondaryEvent * nest::rate_connection_delayed< targetidentifierT >::get_secondary_event()
void nest::rate_connection_delayed< targetidentifierT >::check_connection(Node &s, Node &t, size_t receptor_type, const CommonPropertiesType &)
References nest::Node::handles_test_event, nest::names::receptor_type, nest::Node::sends_secondary_event, nest::Event::set_sender.
void nest::rate_connection_delayed< targetidentifierT >::send(Event &e, size_t t, const CommonSynapseProperties &)
Send an event to the receiver of this connection.
e The event to send p The port under which this connection is stored in the Connector.
References numerics::e, nest::rate_connection_delayed< targetidentifierT >::get_delay_steps, nest::rate_connection_delayed< targetidentifierT >::get_rport, nest::rate_connection_delayed< targetidentifierT >::get_target.
void nest::rate_connection_delayed< targetidentifierT >::get_status(DictionaryDatum &d) const
References nest::names::d, nest::names::size_of, nest::names::weight.
void nest::rate_connection_delayed< targetidentifierT >::set_status(const DictionaryDatum &d, ConnectorModel &cm)
References nest::names::d, nest::names::weight.
void nest::rate_connection_delayed< targetidentifierT >::set_weight(double w)
References nest::names::w.
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
Referenced by nest::rate_connection_delayed< targetidentifierT >::send.
size_t nest::Connection< targetidentifierT >::get_rport() const
Referenced by nest::rate_connection_delayed< targetidentifierT >::send.
Node* nest::Connection< targetidentifierT >::get_target(const size_t tid) const
Referenced by nest::rate_connection_delayed< targetidentifierT >::send.