nest::SPBuilder
std::string nest::SPBuilder::name_
The name of the SPBuilder; used to identify its properties in the structural_plasticity_synapses kernel attributes.
Referenced by get_name, set_name.
nest::SPBuilder::SPBuilder(NodeCollectionPTR sources, NodeCollectionPTR targets, const DictionaryDatum &conn_spec, const std::vector< DictionaryDatum > &syn_spec)
The SPBuilder is in charge of the creation of synapses during the simulation under the control of the structural plasticity manager.
sources the source nodes on which synapses can be created/deleted targets the target nodes on which synapses can be created/deleted conn_spec connectivity specification syn_spec synapse specifications
References nest::ConnBuilder::use_structural_plasticity_.
const std::string& nest::SPBuilder::get_pre_synaptic_element_name() const
References nest::ConnBuilder::pre_synaptic_element_name_.
Referenced by nest::SPManager::update_structural_plasticity.
const std::string& nest::SPBuilder::get_post_synaptic_element_name() const
References nest::ConnBuilder::post_synaptic_element_name_.
Referenced by nest::SPManager::update_structural_plasticity.
void nest::SPBuilder::set_name(const std::string &name)
References name_.
Referenced by nest::SPManager::set_status.
std::string nest::SPBuilder::get_name() const
References name_.
void nest::SPBuilder::update_delay(long &d) const
Writes the default delay of the connection model, if the SPBuilder only uses the default delay.
If not, the min/max_delay has to be specified explicitly with the kernel status.
References nest::names::d, nest::names::delay, nest::ModelManager::get_connector_defaults, nest::Time::get_steps, nest::kernel, nest::KernelManager::model_manager.
void nest::SPBuilder::sp_connect(const std::vector< size_t > &sources, const std::vector< size_t > &targets)
Only for internal use by SPManager.
References nest::VPManager::get_num_threads, nest::kernel, nest::names::targets, nest::KernelManager::vp_manager.
Referenced by nest::SPManager::create_synapses.
void nest::SPBuilder::connect_() override
Implements the actual connection algorithm.
void nest::SPBuilder::connect_(NodeCollectionPTR sources, NodeCollectionPTR targets)
In charge of dynamically creating the new synapses.
void nest::SPBuilder::connect_(const std::vector< size_t > &sources, const std::vector< size_t > &targets)
In charge of dynamically creating the new synapses.
sources nodes from which synapses can be created targets target nodes for the newly created synapses
References nest::NodeManager::get_node_or_proxy, nest::VPManager::get_thread_id, nest::get_vp_specific_rng, nest::kernel, nest::KernelManager::node_manager, nest::names::target, nest::names::targets, nest::KernelManager::vp_manager.
virtual void nest::ConnBuilder::connect_()=0
Implements the actual connection algorithm.