nest::RingBuffer
std::vector< double > nest::RingBuffer::buffer_
Buffered data.
nest::RingBuffer::RingBuffer()
void nest::RingBuffer::add_value(const long offs, const double)
Add a value to the ring buffer.
offs Arrival time relative to beginning of slice. double Value to add.
Referenced by nest::cm_default::handle.
void nest::RingBuffer::set_value(const long offs, const double)
Set a ring buffer entry to a given value.
offs Arrival time relative to beginning of slice. double Value to set.
double nest::RingBuffer::get_value(const long offs)
Read one value from ring buffer.
offs Offset of element to read within slice. value
References nest::kernel.
double nest::RingBuffer::get_value_wfr_update(const long offs)
Read one value from ring buffer without deleting it afterwards.
offs Offset of element to read within slice. value
References nest::kernel.
void nest::RingBuffer::clear()
Initialize the buffer with noughts.
Also resizes the buffer if necessary.
Referenced by nest::AMPA::pre_run_hook, nest::GABA::pre_run_hook, nest::NMDA::pre_run_hook, nest::AMPA_NMDA::pre_run_hook.
void nest::RingBuffer::resize()
Resize the buffer according to max_thread and max_delay.
New elements are filled with noughts. resize() has no effect if the buffer has the correct size.
References nest::KernelManager::connection_manager, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::kernel.
size_t nest::RingBuffer::size() const
Returns buffer size, for memory measurement.
size_t nest::RingBuffer::get_index_(const long d) const
Obtain buffer index.
delay delivery delay for event index to buffer element into which event should be recorded.