nest::StructuralPlasticityNode
double nest::StructuralPlasticityNode::Ca_t_
Time of the last update of the Calcium concentration in ms.
double nest::StructuralPlasticityNode::Ca_minus_
Value of the calcium concentration [Ca2+] at Ca_t_.
Intracellular calcium concentration has a linear factor to mean electrical activity of 10^2, this means, for example, that a [Ca2+] of 0.2 is equivalent to a mean activity of 20 Hz.
double nest::StructuralPlasticityNode::tau_Ca_
Time constant for exponential decay of the intracellular calcium concentration.
double nest::StructuralPlasticityNode::beta_Ca_
Increase in calcium concentration [Ca2+] for each spike of the neuron.
std::map< Name, SynapticElement > nest::StructuralPlasticityNode::synaptic_elements_map_
Map of the synaptic elements.
nest::StructuralPlasticityNode::StructuralPlasticityNode()
nest::StructuralPlasticityNode::StructuralPlasticityNode(const StructuralPlasticityNode &)
double nest::StructuralPlasticityNode::get_Ca_minus() const override
return the current value of Ca_minus
double nest::StructuralPlasticityNode::get_synaptic_elements(Name n) const override
Get the number of synaptic element for the current Node.
The number of synaptic elements is a double value but the number of actual vacant and connected elements is an integer truncated from this value
References nest::names::n.
int nest::StructuralPlasticityNode::get_synaptic_elements_vacant(Name n) const override
Get the number of synaptic elements of type n which are available for new synapse creation.
References nest::names::n.
int nest::StructuralPlasticityNode::get_synaptic_elements_connected(Name n) const override
Get the number of synaptic element of type n which are currently connected.
References nest::names::n.
std::map< Name, double > nest::StructuralPlasticityNode::get_synaptic_elements() const override
Get the number of all synaptic elements for the current Node.
void nest::StructuralPlasticityNode::update_synaptic_elements(double t) override
Change the number of synaptic elements in the node depending on the dynamics described by the corresponding growth curve.
void nest::StructuralPlasticityNode::decay_synaptic_elements_vacant() override
Delete a certain portion of the vacant synaptic elements which are not in use.
void nest::StructuralPlasticityNode::connect_synaptic_element(Name name, int n) override
Change the number of connected synaptic elements by n.
References nest::names::n.
void nest::StructuralPlasticityNode::get_status(DictionaryDatum &d) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::names::beta_Ca, nest::names::Ca, nest::names::d, nest::names::synaptic_elements, nest::names::tau_Ca.
Referenced by nest::ArchivingNode::get_status.
void nest::StructuralPlasticityNode::set_status(const DictionaryDatum &d) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::beta_Ca, nest::names::Ca, nest::names::clear, nest::names::d, nest::names::synaptic_elements, nest::names::synaptic_elements_param, nest::names::tau_Ca.
Referenced by nest::ArchivingNode::set_status.
double nest::StructuralPlasticityNode::get_tau_Ca() const
Retrieve the current value of tau_Ca which defines the exponential decay constant of the intracellular calcium concentration.
void nest::StructuralPlasticityNode::set_spiketime(Time const &t_sp, double offset=0.0)
Record spike history.
References nest::Time::get_ms, nest::names::offset.
Referenced by nest::ArchivingNode::set_spiketime.
void nest::StructuralPlasticityNode::clear_history()
Clear spike history.
virtual double nest::Node::get_synaptic_elements(Name) const
Get the number of synaptic element for the current Node at Ca_t which corresponds to the time of the last spike.
Return 0.0 if not overridden
virtual std::map< Name, double > nest::Node::get_synaptic_elements() const
Get the number of all synaptic elements for the current Node at time t.
Return an empty map if not overridden