nest::SPManager
double nest::SPManager::structural_plasticity_update_interval_
Time interval for structural plasticity update (creation/deletion of synapses).
bool nest::SPManager::structural_plasticity_enabled_
Indicates whether the Structrual Plasticity functionality is On (True) of Off (False).
std::vector< SPBuilder* > nest::SPManager::sp_conn_builders_
std::vector< GenericGrowthCurveFactory* > nest::SPManager::growthcurve_factories_
GrowthCurve factories, indexed by growthcurvedict_ elements.
DictionaryDatum nest::SPManager::growthcurvedict_
Dictionary for growth rules.
nest::SPManager::SPManager()
nest::SPManager::~SPManager() override
References finalize.
void nest::SPManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
void nest::SPManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
Referenced by ~SPManager.
void nest::SPManager::get_status(DictionaryDatum &) override
References nest::names::allow_autapses, nest::names::allow_multapses, nest::names::d, nest::ModelManager::get_connection_model, nest::ConnectorModel::get_name, nest::names::growth_curves, nest::kernel, nest::names::model, nest::KernelManager::model_manager, nest::names::post_synaptic_element, nest::names::pre_synaptic_element, nest::names::structural_plasticity_synapses, nest::names::structural_plasticity_update_interval, nest::names::synapse_model.
void nest::SPManager::set_status(const DictionaryDatum &) override
Set status of synaptic plasticity variables: synaptic update interval, synapses and synaptic elements.
d Dictionary containing the values to be set
References nest::names::allow_autapses, nest::names::allow_multapses, nest::names::d, nest::ConnBuilder::get_default_delay, nest::kernel, nest::SPBuilder::set_name, nest::names::structural_plasticity_synapses, nest::names::structural_plasticity_update_interval, nest::names::targets.
GrowthCurve * nest::SPManager::new_growth_curve(Name name)
Create a new Growth Curve object using the GrowthCurve Factory.
name which defines the type of NC to be created a new Growth Curve object of the type indicated by name
Referenced by nest::SynapticElement::operator=, nest::SynapticElement::set, nest::SynapticElement::SynapticElement.
void nest::SPManager::register_growth_curve(const std::string &name)
Add a growth curve for MSP.
Referenced by nest::NestModule::init.
void nest::SPManager::disconnect(NodeCollectionPTR sources, NodeCollectionPTR targets, DictionaryDatum &conn_spec, DictionaryDatum &syn_spec)
Disconnect two collections of nodes.
The connection is established on the thread/process that owns the target node. Obtains the right connection builder and performs a synapse deletion according to the specified connection specs. sources Node collection of the source Nodes. targets Node collection of the target Nodes. connectivity Params connectivity Dictionary synapse Params synapse parameters Dictionary conn_spec disconnection specs. For now only all to all and one to one rules are implemented.
References ALL_ENTRIES_ACCESSED, nest::KernelManager::connection_manager, nest::ConnBuilder::disconnect, nest::ConnectionManager::get_conn_builder, nest::VPManager::get_thread_id, nest::kernel, nest::names::rule, nest::ConnectionManager::set_connections_have_changed, nest::ConnBuilder::set_synaptic_element_names, nest::KernelManager::simulation_manager, nest::names::synapse_model, nest::names::targets, nest::SimulationManager::update_connection_infrastructure, nest::KernelManager::vp_manager.
Referenced by nest::disconnect, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::ConnBuilder::single_disconnect_.
void nest::SPManager::disconnect(const size_t snode_id, Node *target, size_t target_thread, const size_t syn_id)
Disconnect two nodes.
The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node. snode_id node ID of the sending Node. target Pointer to target Node. target_thread Thread that hosts the target node. syn_id The synapse model to use.
References nest::KernelManager::connection_manager, nest::ConnectionManager::disconnect, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::names::target_thread, nest::KernelManager::vp_manager.
void nest::SPManager::update_structural_plasticity()
void nest::SPManager::update_structural_plasticity(SPBuilder *)
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, create_synapses, delete_synapses_from_post, delete_synapses_from_pre, nest::SPBuilder::get_post_synaptic_element_name, nest::SPBuilder::get_pre_synaptic_element_name, nest::ConnBuilder::get_synapse_model, get_synaptic_elements, nest::kernel, nest::KernelManager::mpi_manager, nest::ConnectionManager::set_connections_have_changed.
void nest::SPManager::enable_structural_plasticity()
Enable structural plasticity.
References nest::kernel.
Referenced by nest::NestModule::EnableStructuralPlasticity_Function::execute.
void nest::SPManager::disable_structural_plasticity()
Disable structural plasticity.
Referenced by nest::NestModule::DisableStructuralPlasticity_Function::execute.
bool nest::SPManager::is_structural_plasticity_enabled() const
double nest::SPManager::get_structural_plasticity_update_interval() const
long nest::SPManager::builder_min_delay() const
Returns the minimum delay of all SP builders.
This influences the min_delay of the kernel, as the connections are build during the simulation. Hence, the ConnectionManager::min_delay() methods have to respect this delay as well.
References nest::Time::get_steps, nest::names::min, nest::names::min_delay, nest::Time::pos_inf.
long nest::SPManager::builder_max_delay() const
Returns the maximum delay of all SP builders.
This influences the max_delay of the kernel, as the connections are build during the simulation. Hence, the ConnectionManager::max_delay() methods have to respect this delay as well.
References nest::Time::get_steps, nest::names::max, nest::names::max_delay, nest::Time::neg_inf.
bool nest::SPManager::create_synapses(std::vector< size_t > &pre_vacant_id, std::vector< int > &pre_vacant_n, std::vector< size_t > &post_vacant_id, std::vector< int > &post_vacant_n, SPBuilder *sp_conn_builder)
References global_shuffle, serialize_id, nest::SPBuilder::sp_connect.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapses_from_pre(const std::vector< size_t > &pre_deleted_id, std::vector< int > &pre_deleted_n, const size_t synapse_model, const std::string &se_pre_name, const std::string &se_post_name)
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, delete_synapse, nest::ConnectionManager::get_targets, global_shuffle, nest::kernel, nest::KernelManager::mpi_manager, nest::names::synapse_model.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapses_from_post(std::vector< size_t > &post_deleted_id, std::vector< int > &post_deleted_n, size_t synapse_model, std::string se_pre_name, std::string se_post_name)
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, delete_synapse, nest::ConnectionManager::get_sources, global_shuffle, nest::kernel, nest::KernelManager::mpi_manager, nest::names::synapse_model.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapse(size_t source, size_t target, long syn_id, std::string se_pre_name, std::string se_post_name)
References nest::KernelManager::connection_manager, nest::ConnectionManager::disconnect, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::names::target_thread, nest::KernelManager::vp_manager.
Referenced by delete_synapses_from_post, delete_synapses_from_pre.
void nest::SPManager::get_synaptic_elements(std::string se_name, std::vector< size_t > &se_vacant_id, std::vector< int > &se_vacant_n, std::vector< size_t > &se_deleted_id, std::vector< int > &se_deleted_n)
References nest::SparseNodeArray::begin, nest::SparseNodeArray::end, nest::NodeManager::get_local_nodes, nest::VPManager::get_num_threads, nest::Node::get_synaptic_elements_vacant, nest::kernel, nest::names::n, nest::KernelManager::node_manager, nest::NodeManager::size, nest::KernelManager::vp_manager.
Referenced by update_structural_plasticity.
void nest::SPManager::serialize_id(std::vector< size_t > &id, std::vector< int > &n, std::vector< size_t > &res)
References nest::names::n.
Referenced by create_synapses.
void nest::SPManager::global_shuffle(std::vector< size_t > &v)
Referenced by create_synapses, delete_synapses_from_post, delete_synapses_from_pre.
void nest::SPManager::global_shuffle(std::vector< size_t > &v, size_t n)
References nest::get_rank_synced_rng, nest::names::N, nest::names::n, nest::BaseRandomGenerator::ulrand.