nest::MaskedLayer
std::shared_ptr< Ntree< D, size_t > > nest::MaskedLayer< D >::ntree_
Referenced by nest::MaskedLayer< D >::MaskedLayer.
MaskDatum nest::MaskedLayer< D >::mask_
Referenced by nest::MaskedLayer< D >::MaskedLayer.
nest::MaskedLayer< D >::MaskedLayer(Layer< D > &layer, const MaskDatum &mask, bool allow_oversized, NodeCollectionPTR node_collection)
Regular constructor.
layer The layer to mask mask The mask to apply to the layer allow_oversized If true, allow larges masks than layers when using periodic b.c. node_collection NodeCollection of the layer
References nest::MaskedLayer< D >::check_mask_, nest::Layer< D >::get_global_positions_ntree, nest::MaskedLayer< D >::ntree_.
nest::MaskedLayer< D >::MaskedLayer(Layer< D > &layer, const MaskDatum &mask, bool allow_oversized, Layer< D > &target, NodeCollectionPTR node_collection)
Constructor for applying "converse" mask to layer.
To be used for applying a mask for the target layer to the source layer. The mask will be mirrored about the origin, and settings for periodicity for the target layer will be applied to the source layer. layer The layer to mask (source layer) mask The mask to apply to the layer allow_oversized If true, allow larges masks than layers when using periodic b.c. target The layer which the given mask is defined for (target layer) node_collection NodeCollection of the layer
References nest::MaskedLayer< D >::check_mask_, nest::Layer< D >::get_global_positions_ntree, nest::MaskedLayer< D >::mask_, nest::MaskedLayer< D >::ntree_, nest::names::target.
nest::MaskedLayer< D >::~MaskedLayer()
Ntree< D, size_t >::masked_iterator nest::MaskedLayer< D >::begin(const Position< D > &anchor)
Iterate over nodes inside mask.
anchor Position to apply mask to an iterator for the nodes inside the mask centered on the anchor position
References nest::names::anchor, numerics::e.
Referenced by nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, nest::Layer< D >::get_global_nodes, nest::Layer< D >::get_global_positions_vector.
Ntree< D, size_t >::masked_iterator nest::MaskedLayer< D >::end()
end iterator
Referenced by nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, nest::Layer< D >::get_global_nodes, nest::Layer< D >::get_global_positions_vector.
void nest::MaskedLayer< D >::check_mask_(Layer< D > &layer, bool allow_oversized)
Will check that the mask can be applied to the layer.
The mask must have the same dimensionality as the layer, and a grid mask may only be applied to a grid layer. Unless the allow_oversized flag is set, the mask must also not be larger than the layer in case of periodic boundary conditions. Will throw an exception if the mask does not fit. layer The layer to check for allow_oversized If true, oversized masks are allowed
References nest::GridLayer< D >::get_dims, nest::Layer< D >::get_extent, nest::GridMask< D >::get_lower_right, nest::Layer< D >::get_periodic_mask, nest::GridMask< D >::get_upper_left, nest::names::lower_left, nest::Box< D >::lower_left, nest::names::mask, nest::names::upper_right, nest::Box< D >::upper_right, nest::names::y.
Referenced by nest::MaskedLayer< D >::MaskedLayer.