nest::TargetDataFields
unsigned int nest::TargetDataFields::lcid_
unsigned int nest::TargetDataFields::tid_
unsigned int nest::TargetDataFields::syn_id_
void nest::TargetDataFields::set_lcid(const size_t lcid)
Sets the local connection ID.
size_t nest::TargetDataFields::get_lcid() const
Returns the local connection ID.
Referenced by nest::TargetTable::add_target.
void nest::TargetDataFields::set_tid(const size_t tid)
Sets the target ID.
size_t nest::TargetDataFields::get_tid() const
Returns the target ID.
Referenced by nest::TargetTable::add_target.
void nest::TargetDataFields::set_syn_id(const synindex syn_id)
Sets the synapse-type ID.
synindex nest::TargetDataFields::get_syn_id() const
Returns the synapse-type ID.
Referenced by nest::TargetTable::add_target.