nest::Event
size_t nest::Event::sender_node_id_
node ID of sender or 0
Referenced by get_sender_node_id, retrieve_sender_node_id_from_source_table, set_sender_node_id.
SpikeData nest::Event::sender_spike_data_
spike data of sender node, in some cases required to retrieve node ID
Referenced by retrieve_sender_node_id_from_source_table, set_sender_node_id_info.
Node* nest::Event::sender_
Pointer to sender or nullptr.
Referenced by get_sender, nest::DSSpikeEvent::operator(), nest::DSCurrentEvent::operator(), sender_is_valid, set_sender.
Node* nest::Event::receiver_
Pointer to receiver or nullptr.
Referenced by get_receiver, get_receiver_node_id, nest::SpikeEvent::operator(), nest::WeightRecorderEvent::operator(), nest::RateEvent::operator(), nest::CurrentEvent::operator(), nest::DataLoggingRequest::operator(), nest::DataLoggingReply::operator(), nest::ConductanceEvent::operator(), nest::DoubleDataEvent::operator(), nest::GapJunctionEvent::operator(), nest::InstantaneousRateConnectionEvent::operator(), nest::DelayedRateConnectionEvent::operator(), nest::DiffusionConnectionEvent::operator(), receiver_is_valid, set_receiver.
size_t nest::Event::p_
Sender port number.
The sender port is used as a unique identifier for the connection. The receiver of an event can use the port number to obtain data from the sender. The sender uses this number to locate target-specific information. A negative port number indicates an unknown port.
Referenced by get_port, set_port.
size_t nest::Event::rp_
Receiver port number (r-port).
The receiver port (r-port) can be used by the receiving Node to distinguish incoming connections. E.g. the r-port number can be used by Events to access specific parts of a Node. In most cases, however, this port will no be used. The use of this port number is optional. An r-port number of 0 indicates that the port is not used.
Referenced by get_rport, set_rport.
long nest::Event::d_
Transmission delay.
Number of simulations steps that pass before the event is delivered at the receiver. The delay must be at least 1.
Referenced by get_delay_steps, get_rel_delivery_steps, is_valid, set_delay_steps.
Time nest::Event::stamp_
Time stamp.
The time stamp specifies the absolute time when the event shall arrive at the target.
Referenced by get_rel_delivery_steps, get_stamp, set_stamp.
long nest::Event::stamp_steps_
Time stamp in steps.
Caches the value of stamp in steps for efficiency. Needs to be declared mutable since it is modified by a const function (get_rel_delivery_steps).
Referenced by get_rel_delivery_steps, set_stamp.
double nest::Event::offset_
Offset for precise spike times.
offset_ specifies a correction to the creation time. If the resolution of stamp is not sufficiently precise, this attribute can be used to correct the creation time. offset_ has to be in [0, h).
Referenced by get_offset, set_offset.
double nest::Event::w_
Weight of the connection.
Referenced by get_weight, set_weight.
nest::Event::Event()
virtual nest::Event::~Event()
virtual Event* nest::Event::clone() const =0
virtual void nest::Event::operator()()=0
Deliver the event to receiver.
This operator calls the handler for the specific event type at the receiver.
void nest::Event::set_receiver(Node &)
Change pointer to receiving Node.
References receiver_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
Node & nest::Event::get_receiver() const
Return reference to receiving Node.
References receiver_.
size_t nest::Event::get_receiver_node_id() const
Return node ID of receiving Node.
References nest::Node::get_node_id, receiver_.
Node & nest::Event::get_sender() const
Return reference to sending Node.
This will cause a segmentation fault if sender has not been set via set_sender().
References sender_.
void nest::Event::set_sender(Node &)
Change pointer to sending Node.
References sender_.
Referenced by nest::diffusion_connection< targetidentifierT >::check_connection, nest::gap_junction< targetidentifierT >::check_connection, nest::rate_connection_delayed< targetidentifierT >::check_connection, nest::rate_connection_instantaneous< targetidentifierT >::check_connection, nest::Connector< ConnectionT >::send_weight_event.
size_t nest::Event::get_sender_node_id() const
Sender is local.
Return node ID of sending Node. This will trigger an assertion if sender node id has not been set.
References sender_node_id_.
size_t nest::Event::retrieve_sender_node_id_from_source_table() const
Sender is not local.
Retrieve node ID of sending Node from SourceTable and return it.
References nest::KernelManager::connection_manager, nest::SpikeData::get_lcid, nest::ConnectionManager::get_source_node_id, nest::SpikeData::get_syn_id, nest::SpikeData::get_tid, nest::kernel, sender_node_id_, sender_spike_data_.
void nest::Event::set_sender_node_id(const size_t)
Change node ID of sending Node.
References sender_node_id_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
void nest::Event::set_sender_node_id_info(const size_t tid, const synindex syn_id, const size_t lcid)
Set tid, syn_id, lcid of spike_data_.
These are required to retrieve the Node ID of a non-local sender from the SourceTable.
References sender_spike_data_, nest::SpikeData::set.
Time const & nest::Event::get_stamp() const
Return time stamp of the event.
The stamp denotes the time when the event was created. The resolution of Stamp is limited by the time base of the simulation kernel (class nest::Time). If this resolution is not fine enough, the creation time can be corrected by using the time attribute.
References stamp_.
void nest::Event::set_delay_steps(long)
Set the transmission delay of the event.
The delay refers to the time until the event is expected to arrive at the receiver. t delay.
References nest::names::d, d_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
long nest::Event::get_delay_steps() const
Return transmission delay of the event.
The delay refers to the time until the event is expected to arrive at the receiver.
References d_.
long nest::Event::get_rel_delivery_steps(const Time &t) const
Relative spike delivery time in steps.
Returns the delivery time of the spike relative to a given time in steps. Causality commands that the result should not be negative. stamp + delay - 1 - t in steps Time reference time NEST Time Memo, Rule 3
References d_, nest::Time::get_steps, stamp_, stamp_steps_.
size_t nest::Event::get_port() const
Return the sender port number of the event.
This function returns the number of the port over which the Event was sent. A negative return value indicates that no port number was available.
References p_.
size_t nest::Event::get_rport() const
Return the receiver port number of the event.
This function returns the number of the r-port over which the Event was sent. A return value of 0 indicates that the r-port is not used.
References rp_.
void nest::Event::set_port(size_t p)
Set the port number.
Each event carries the number of the port over which the event is sent. When a connection is established, it receives a unique ID from the sender. This number has to be stored in each Event object. p Port number of the connection, or -1 if unknown.
References nest::names::p, p_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
void nest::Event::set_rport(size_t p)
Set the receiver port number (r-port).
When a connection is established, the receiving Node may issue a port number (r-port) to distinguish the incomin connection. By the default, the r-port is not used and its port number defaults to zero. p Receiver port number of the connection, or 0 if unused.
References rp_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
double nest::Event::get_offset() const
Return the creation time offset of the Event.
Each Event carries the exact time of creation. This time need not coincide with an integral multiple of the temporal resolution. Rather, Events may be created at any point in time.
References offset_.
void nest::Event::set_offset(double t)
Set the creation time of the Event.
Each Event carries the exact time of creation in realtime. This time need not coincide with an integral multiple of the temporal resolution. Rather, Events may be created at any point in time. t Creation time in realtime. t has to be in [0, h).
References offset_.
double nest::Event::get_weight() const
Return the weight.
References w_.
void nest::Event::set_weight(double t)
Set weight of the event.
References nest::names::w, w_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
virtual void nest::Event::set_drift_factor(double)
Set drift_factor of the event (see DiffusionConnectionEvent).
virtual void nest::Event::set_diffusion_factor(double)
Set diffusion_factor of the event (see DiffusionConnectionEvent).
bool nest::Event::sender_is_valid() const
Returns true if the pointer to the sender node is valid.
References sender_.
Referenced by is_valid.
bool nest::Event::receiver_is_valid() const
Returns true if the pointer to the receiver node is valid.
References receiver_.
Referenced by is_valid.
bool nest::Event::is_valid() const
Check integrity of the event.
This function returns true, if all data, in particular sender and receiver pointers are correctly set.
References d_, receiver_is_valid, sender_is_valid.
void nest::Event::set_stamp(Time const &)
Set the time stamp of the event.
The time stamp refers to the time when the event was created.
References stamp_, stamp_steps_.
Referenced by nest::ConnectionManager::deliver_secondary_events, nest::multimeter::handle, nest::Connector< ConnectionT >::send_weight_event.