name: Source Workflow

on:
  workflow_dispatch:
  release:
    types: [prereleased]

run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          repository: nest/nest-simulator-examples
          event-type: Integration-with-Automation
      - name: my-step
        run: 'echo ${{ github.actor }} Hello !'
